### PR TITLE
Fisher-Yates shuffle with fn(arr)

### PR DESCRIPTION
**Pull request by MoreOutput**

### CODE REVIEW

**Comment by tejasmanohar** [comment]
Sorry, we don't want code here :laughing: -- Make another repo, publish to NPM, and PR us with the link!

**Comment by MoreOutput** [comment]
My mistake. Misunderstood a HN comment.

**Comment by tejasmanohar** [comment]
Ah. Sorry about that, but yeah def PR us again after publishing :+1:

**Comment by MoreOutput** [comment]
@tejasmanohar PR is in.

**Pull request closed without merging**
