### PR TITLE
Added (and categorized) some cryptographic algorithms

### PR DESCRIPTION
**Pull request by qw3rtman**
Added some cryptographic algorithms, including MD5, AES, Blowfish, and bcrypt and began categorization.

### CODE REVIEW

**Comment by iangcarroll** [comment]
Perhaps the SHA1 and SHA2 packages could also be added. Probably don't want to suggest MD5 anyway (collisions).

**Comment by tejasmanohar** [comment]
@iangcarroll sounds like a good PR :+1:

**Comment by qw3rtman** [comment]
I was a bit apprehensive about adding MD5, but I thought it would add to the comprehensiveness of the list.

**Comment by tejasmanohar** [comment]
Yeah, it does. It works for some things. Just not the **best**.

**Pull request merged**
